monitor=,preferred,auto,auto
monitor=eDP-1,highres,auto,1.666667
monitor=HDMI-A-1,highres,auto,1.666667

general {
    col.active_border = rgb(44475a) rgb(bd93f9) 90deg
    col.inactive_border = rgba(44475aaa)
    col.nogroup_border = rgba(282a36dd)
    col.nogroup_border_active = rgb(bd93f9) rgb(44475a) 90deg
    border_size = 2
    gaps_in = 0
    gaps_out = 0
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

group {
    groupbar {
        col.active = rgb(bd93f9) rgb(44475a) 90deg
        col.inactive = rgba(282a36dd)
    }
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}

# will reset the submap, which will return to the global submap
submap = reset

xwayland {
  force_zero_scaling = true
}

source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/startup.conf
source = ~/.config/hypr/configs/windowrule.conf
source = ~/.config/hypr/configs/layerrule.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/decoration.conf
