#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

# clear rule
flush ruleset

define RESERVED_IP = {
  192.168.0.0/16,
  10.0.0.0/8,
  100.64.0.0/10,
  127.0.0.0/8,
  169.254.0.0/16,
  172.16.0.0/12,
  172.168.0.0/16,
  192.0.0.0/24,
  224.0.0.0/4,
  240.0.0.0/4,
  255.255.255.255/32
}

table ip xray {
  chain prerouting {
    type filter hook prerouting priority mangle; policy accept;
    udp dport 53 mark set 1 tproxy to 127.0.0.1:9898 accept
    ip daddr $RESERVED_IP return
    meta l4proto {tcp, udp} mark set 1 tproxy to 127.0.0.1:9898 accept
  }
  chain output {
    type route hook output priority mangle; policy accept;
    udp dport 53 mark set 1 accept
    meta skuid "sing-box" accept
    ip daddr $RESERVED_IP return
    meta l4proto {tcp, udp} mark set 1 accept
  }
}
