#!/usr/bin/env python

import hashlib
import json
import os
import sqlite3
import sys

import requests
from rich import print

workspace_dir = os.path.dirname(__file__)


def query_by_id(word: str):
    conn = sqlite3.connect(workspace_dir + "/xhup.db")
    c = conn.cursor()
    cursor = c.execute(
        'SELECT count(*) FROM sqlite_master WHERE type = "table" AND name = "xhup"'
    )
    if not cursor.fetchone()[0]:
        c.execute("CREATE TABLE xhup(ID CHAR(10) PRIMARY KEY NOT NULL, RESULT text);")

    c = conn.cursor()
    cursor = c.execute(f'SELECT RESULT from xhup WHERE ID = "{word}"')
    db_data = cursor.fetchone()

    if db_data:
        return json.loads(db_data[0])


def create(word: str, result: str):
    conn = sqlite3.connect(workspace_dir + "/xhup.db")
    c = conn.cursor()
    cursor = c.execute(
        f"INSERT INTO xhup (ID, RESULT) VALUES (?, ?);",
        (
            word,
            result,
        ),
    )
    conn.commit()
    cursor.close()


if len(sys.argv) > 1:
    md5 = hashlib.md5()
    w = sys.argv[1][:1]
    url = "http://www.xhup.club/Xhup/Search/searchCode"
    md5.update(f"fjc_xhup{w}".encode())
    data = {"search_word": w, "sign": md5.hexdigest()}
    h = {
        "Host": "www.xhup.club",
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0",
        "Accept": "application/json, text/plain, */*",
        "Accept-Language": "en-US,en;q=0.5",
        "Accept-Encoding": "gzip, deflate",
        "Content-Type": "application/x-www-form-urlencoded",
        "Content-Length": "59",
        "Origin": "http://react.xhup.club",
        "Connection": "keep-alive",
        "Referer": "http://react.xhup.club/",
    }
    r = query_by_id(w)
    if not r:
        r = requests.post(url, data=data, headers=h).json()
        create(w, json.dumps(r))
    # {'msg': 'success', 'list_dz': [['查：\u3000\u3000iama- vama', '木\u3000日\u3000一', '木', '一', 'm', 'a', '查']], 'list_ci': [], 'notInMbList': [], 'noResultCount': 0}
    print()
    list_dz = r["list_dz"][0]
    print(f"[yellow]{w}  [/yellow]", end="  ")

    pin_xie = list_dz[0][2:].replace("\u3000", "")
    print(f"[bold][red]{pin_xie}[/red][/bold]")

    print("────────────────────")

    print("[blue]拆分[/blue]", end="  ")
    print(list_dz[1])
    print("[blue]首末[/blue]", end="  ")
    print(list_dz[2], end="  ")
    print(list_dz[3])
    print("[blue]编码[/blue]", end="  ")
    print(list_dz[4], end="  ")
    print(list_dz[5])
