[general]
import = [
  "~/.config/alacritty/dracula.toml",
  "~/.config/alacritty/keybindings.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

normal = { family = "VictorMono Nerd Font Mono", style = "Regular" }
bold = { family = "VictorMono Nerd Font Mono", style = "Bold" }
italic = { family = "VictorMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "VictorMono Nerd Font Mono", style = "Bold Italic" }

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[cursor]
style = { shape = "Underline", blinking = "Always" }
unfocused_hollow = true
thickness = 0.3

[window]
opacity = 1.0
padding = { x = 30, y = 30 }
dimensions = { columns = 100, lines = 30 }
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false
