[colors.primary]
background = "#282A36"
foreground = "#DADBD7"

[colors.cursor]
text = "#282A36"
cursor = "#BD93F9"

[colors.selection]
text = "#282A36"
background = "#6272A4"

[colors.normal]
black = "#63656C"
red = "#FF5555"
green = "#50FA7B"
yellow = "#F1FA8C"
blue = "#6272A4"
magenta = "#FF79C6"
cyan = "#8BE9FD"
white = "#DADBD7"

[colors.bright]
black = "#818287"
red = "#FE7674"
green = "#72FA93"
yellow = "#F2FAA0"
blue = "#808DB4"
magenta = "#FE92CF"
cyan = "#A1ECFB"
white = "#F8F8F2"

[colors.dim]
black = "#464751"
red = "#D44C4F"
green = "#48D06D"
yellow = "#C9D07B"
blue = "#56648E"
magenta = "#D469A9"
cyan = "#77C3D5"
white = "#BDBDBC"
