[keyboard]
bindings = [
  { key= "V",        mods= "Command",     action="Paste"   },
  { key= "X",        mods= "Command",     chars= "\u001bx" },

  { key= "A",         mods= "Alt",        chars= "\u001ba" },
  { key= "B",         mods= "Alt",        chars= "\u001bb" },
  { key= "C",         mods= "Alt",        chars= "\u001bc" },
  { key= "D",         mods= "Alt",        chars= "\u001bd" },
  { key= "E",         mods= "Alt",        chars= "\u001be" },
  { key= "F",         mods= "Alt",        chars= "\u001bf" },
  { key= "G",         mods= "Alt",        chars= "\u001bg" },
  { key= "H",         mods= "Alt",        chars= "\u001bh" },
  { key= "I",         mods= "Alt",        chars= "\u001bi" },
  { key= "J",         mods= "Alt",        chars= "\u001bj" },
  { key= "K",         mods= "Alt",        chars= "\u001bk" },
  { key= "L",         mods= "Alt",        chars= "\u001bl" },
  { key= "M",         mods= "Alt",        chars= "\u001bm" },
  { key= "N",         mods= "Alt",        chars= "\u001bn" },
  { key= "O",         mods= "Alt",        chars= "\u001bo" },
  { key= "P",         mods= "Alt",        chars= "\u001bp" },
  { key= "Q",         mods= "Alt",        chars= "\u001bq" },
  { key= "R",         mods= "Alt",        chars= "\u001br" },
  { key= "S",         mods= "Alt",        chars= "\u001bs" },
  { key= "T",         mods= "Alt",        chars= "\u001bt" },
  { key= "U",         mods= "Alt",        chars= "\u001bu" },
  { key= "V",         mods= "Alt",        chars= "\u001bv" },
  { key= "W",         mods= "Alt",        chars= "\u001bw" },
  { key= "Y",         mods= "Alt",        chars= "\u001by" },
  { key= "Z",         mods= "Alt",        chars= "\u001bz" },

  { key= "A",         mods= "Alt|Shift",  chars= "\u001bA" },
  { key= "B",         mods= "Alt|Shift",  chars= "\u001bB" },
  { key= "C",         mods= "Alt|Shift",  chars= "\u001bC" },
  { key= "D",         mods= "Alt|Shift",  chars= "\u001bD" },
  { key= "E",         mods= "Alt|Shift",  chars= "\u001bE" },
  { key= "F",         mods= "Alt|Shift",  chars= "\u001bF" },
  { key= "G",         mods= "Alt|Shift",  chars= "\u001bG" },
  { key= "H",         mods= "Alt|Shift",  chars= "\u001bH" },
  { key= "I",         mods= "Alt|Shift",  chars= "\u001bI" },
  { key= "J",         mods= "Alt|Shift",  chars= "\u001bJ" },
  { key= "K",         mods= "Alt|Shift",  chars= "\u001bK" },
  { key= "L",         mods= "Alt|Shift",  chars= "\u001bL" },
  { key= "M",         mods= "Alt|Shift",  chars= "\u001bM" },
  { key= "N",         mods= "Alt|Shift",  chars= "\u001bN" },
  { key= "O",         mods= "Alt|Shift",  chars= "\u001bO" },
  { key= "P",         mods= "Alt|Shift",  chars= "\u001bP" },
  { key= "Q",         mods= "Alt|Shift",  chars= "\u001bQ" },
  { key= "R",         mods= "Alt|Shift",  chars= "\u001bR" },
  { key= "S",         mods= "Alt|Shift",  chars= "\u001bS" },
  { key= "T",         mods= "Alt|Shift",  chars= "\u001bT" },
  { key= "U",         mods= "Alt|Shift",  chars= "\u001bU" },
  { key= "V",         mods= "Alt|Shift",  chars= "\u001bV" },
  { key= "W",         mods= "Alt|Shift",  chars= "\u001bW" },
  { key= "Y",         mods= "Alt|Shift",  chars= "\u001bY" },
  { key= "Z",         mods= "Alt|Shift",  chars= "\u001bZ" },

  { key= "Home",                          chars= "\u001bOH",   mode= "AppCursor"   },
  { key= "Home",                          chars= "\u001b[1~",  mode= "~AppCursor"  },
  { key= "End",                           chars= "\u001bOF",   mode= "AppCursor"   },
  { key= "End",                           chars= "\u001b[4~",  mode= "~AppCursor"  },
  { key= "PageUp",                        chars= "\u001b[5~"                     },
  { key= "PageDown",                      chars= "\u001b[6~"                     },
  { key= "Left",      mods= "Shift",      chars= "\u001b[1;2D"                   },
  { key= "Left",      mods= "Control",    chars= "\u001b[1;5D"                   },
  { key= "Left",      mods= "Alt",        chars= "\u001b[1;3D"                   },
  { key= "Left",                          chars= "\u001b[D",   mode= "~AppCursor"  },
  { key= "Left",                          chars= "\u001bOD",   mode= "AppCursor"   },
  { key= "Right",     mods= "Shift",      chars= "\u001b[1;2C"                   },
  { key= "Right",     mods= "Control",    chars= "\u001b[1;5C"                   },
  { key= "Right",     mods= "Alt",        chars= "\u001b[1;3C"                   },
  { key= "Right",                         chars= "\u001b[C",   mode= "~AppCursor"  },
  { key= "Right",                         chars= "\u001bOC",   mode= "AppCursor"   },
  { key= "Up",        mods= "Shift",      chars= "\u001b[1;2A"                   },
  { key= "Up",        mods= "Control",    chars= "\u001b[1;5A"                   },
  { key= "Up",        mods= "Alt",        chars= "\u001b[1;3A"                   },
  { key= "Up",                            chars= "\u001b[A",   mode= "~AppCursor"  },
  { key= "Up",                            chars= "\u001bOA",   mode= "AppCursor"   },
  { key= "Down",      mods= "Shift",      chars= "\u001b[1;2B"                   },
  { key= "Down",      mods= "Control",    chars= "\u001b[1;5B"                   },
  { key= "Down",      mods= "Alt",        chars= "\u001b[1;3B"                   },
  { key= "Down",                          chars= "\u001b[B",   mode= "~AppCursor"  },
  { key= "Down",                          chars= "\u001bOB",   mode= "AppCursor"   },
  { key= "Tab",       mods= "Shift",      chars= "\u001b[Z"                      },
  { key= "F1",                            chars= "\u001bOP"                      },
  { key= "F2",                            chars= "\u001bOQ"                      },
  { key= "F3",                            chars= "\u001bOR"                      },
  { key= "F4",                            chars= "\u001bOS"                      },
  { key= "F5",                            chars= "\u001b[15~"                    },
  { key= "F6",                            chars= "\u001b[17~"                    },
  { key= "F7",                            chars= "\u001b[18~"                    },
  { key= "F8",                            chars= "\u001b[19~"                    },
  { key= "F9",                            chars= "\u001b[20~"                    },
  { key= "F10",                           chars= "\u001b[21~"                    },
  { key= "F11",                           chars= "\u001b[23~"                    },
  { key= "F12",                           chars= "\u001b[24~"                    },
  { key= "Back",                          chars= "\u007f"                        },
  { key= "Back",      mods= "Alt",        chars= "\u001b\u007f"                    },
  { key= "Insert",                        chars= "\u001b[2~"                     },
  { key= "Delete",                        chars= "\u001b[3~",  mode= "AppKeypad"   },
  { key= "Delete",                        chars= "\u001b[P",   mode= "~AppKeypad"  },

  { key= "Key0",      mods= "Alt",       chars= "\u001b0" },
  { key= "Key1",      mods= "Alt",       chars= "\u001b1" },
  { key= "Key2",      mods= "Alt",       chars= "\u001b2" },
  { key= "Key3",      mods= "Alt",       chars= "\u001b3" },
  { key= "Key4",      mods= "Alt",       chars= "\u001b4" },
  { key= "Key5",      mods= "Alt",       chars= "\u001b5" },
  { key= "Key6",      mods= "Alt",       chars= "\u001b6" },
  { key= "Key7",      mods= "Alt",       chars= "\u001b7" },
  { key= "Key8",      mods= "Alt",       chars= "\u001b8" },
  { key= "Key9",      mods= "Alt",       chars= "\u001b9" },

  { key= "Key0",      mods= "Alt|Shift", chars= "\u001b!" },
  { key= "Key1",      mods= "Alt|Shift", chars= "\u001b@" },
  { key= "Key2",      mods= "Alt|Shift", chars= "\u001b#" },
  { key= "Key3",      mods= "Alt|Shift", chars= "\u001b$" },
  { key= "Key4",      mods= "Alt|Shift", chars= "\u001b%" },
  { key= "Key5",      mods= "Alt|Shift", chars= "\u001b^" },
  { key= "Key6",      mods= "Alt|Shift", chars= "\u001b&" },
  { key= "Key7",      mods= "Alt|Shift", chars= "\u001b*" },
  { key= "Key8",      mods= "Alt|Shift", chars= "\u001b(" },
  { key= "Key9",      mods= "Alt|Shift", chars= "\u001b)" },

  { key= "Key0",      mods= "Command",   chars= "\u00080" },
  { key= "Key1",      mods= "Command",   chars= "\u00081" },
  { key= "Key2",      mods= "Command",   chars= "\u00082" },
  { key= "Key3",      mods= "Command",   chars= "\u00083" },
  { key= "Key4",      mods= "Command",   chars= "\u00084" },
  { key= "Key5",      mods= "Command",   chars= "\u00085" },
  { key= "Key6",      mods= "Command",   chars= "\u00086" },
  { key= "Key7",      mods= "Command",   chars= "\u00087" },
  { key= "Key8",      mods= "Command",   chars= "\u00088" },
  { key= "Key9",      mods= "Command",   chars= "\u00089" },

  { key= "Semicolon", mods= "Alt",       chars= "\u001b;" },
  { key= "Comma",     mods= "Alt",       chars= "\u001b," },
  { key= "Period",    mods= "Alt",       chars= "\u001b." },
  { key= "LBracket",  mods= "Alt",       chars= "\u001b[" },
  { key= "RBracket",  mods= "Alt",       chars= "\u001b]" },
  { key= "Slash",     mods= "Alt",       chars= "\u001b/" },
  { key= "Space",     mods= "Alt",       chars= "\u001b " },
  { key= "Backslash", mods= "Alt",       chars= "\u001b\\" },

  { key= "Semicolon", mods= "Alt|Shift", chars= "\u001b=" },
  { key= "Comma",     mods= "Alt|Shift", chars= "\u001b<" },
  { key= "Period",    mods= "Alt|Shift", chars= "\u001b>" },
  { key= "LBracket",  mods= "Alt|Shift", chars= "\u001b{" },
  { key= "RBracket",  mods= "Alt|Shift", chars= "\u001b}" },
  { key= "Slash",     mods= "Alt|Shift", chars= "\u001b?" },
  { key= "Backslash", mods= "Alt|Shift", chars= "\u001b|" }
]

